'HASH: 2D006BBFC49D6A9AB2B5AF840B0290CA
'MACRO: FILIAIS_TIPOPRESTADOR

'SMS 59509 - Matheus - 18/08/2006

'SMS 87108 - Ricardo Rocha - 05/10/2007 - Modificado LocalWhere para WEB
Public Sub TABLE_BeforeEdit(CanContinue As Boolean)
	If WebMode Then
		TIPOPRESTADOR.WebLocalWhere = "A.HANDLE NOT IN (SELECT TIPOPRESTADOR FROM FILIAIS_TIPOPRESTADOR WHERE FILIAL = @CAMPO(FILIAL))"
	ElseIf VisibleMode Then
		TIPOPRESTADOR.LocalWhere = "HANDLE NOT IN (SELECT TIPOPRESTADOR FROM FILIAIS_TIPOPRESTADOR WHERE FILIAL = @FILIAL)"
	End If
End Sub

Public Sub TABLE_BeforeInsert(CanContinue As Boolean)
	If WebMode Then
		TIPOPRESTADOR.WebLocalWhere = "A.HANDLE NOT IN (SELECT TIPOPRESTADOR FROM FILIAIS_TIPOPRESTADOR WHERE FILIAL = @CAMPO(FILIAL))"
	ElseIf VisibleMode Then
		TIPOPRESTADOR.LocalWhere = "HANDLE NOT IN (SELECT TIPOPRESTADOR FROM FILIAIS_TIPOPRESTADOR WHERE FILIAL = @FILIAL)"
	End If
End Sub
