'HASH: 4A1EBE6ED64DD205543A98E5914970D3
 
'MACRO: FILIAIS_TIPOGUIA

'SMS 59509 - Matheus - 18/08/2006
Public Sub TABLE_BeforeEdit(CanContinue As Boolean)
	If WebMode Then
		TIPOGUIA.WebLocalWhere = "A.HANDLE NOT IN (SELECT TIPOGUIA FROM FILIAIS_TIPOGUIA WHERE FILIAL = @CAMPO(FILIAL)"
	ElseIf VisibleMode Then
		TIPOGUIA.LocalWhere = "HANDLE NOT IN (SELECT TIPOGUIA FROM FILIAIS_TIPOGUIA WHERE FILIAL = @FILIAL)"
	End If
End Sub

Public Sub TABLE_BeforeInsert(CanContinue As Boolean)
	If WebMode Then
		TIPOGUIA.WebLocalWhere = "A.HANDLE NOT IN (SELECT TIPOGUIA FROM FILIAIS_TIPOGUIA WHERE FILIAL = @CAMPO(FILIAL)"
	ElseIf VisibleMode Then
		TIPOGUIA.LocalWhere = "HANDLE NOT IN (SELECT TIPOGUIA FROM FILIAIS_TIPOGUIA WHERE FILIAL = @FILIAL)"
	End If
End Sub
