'HASH: 607C7E0F3116109AAFC382E61D383FDD
'Macro: SAM_REAJUSTEPRC


Public Sub TABLE_AfterInsert()
  If NodeInternalCode = 458795 Then
    CurrentQuery.FieldByName("FILIAL").Value = RecordHandleOfTable("FILIAIS")
  End If

End Sub

Public Sub TABLE_AfterScroll()
End Sub

Public Sub TABLE_BeforeDelete(CanContinue As Boolean)

  Dim DEL As Object
  Dim SQL As Object
  Set SQL = NewQuery
  Set DEL = NewQuery

  Dim T(17) As String
  T(01) = "DELETE FROM SAM_REAJUSTEPRC_ESTADO_AN  WHERE REAJUSTEPRCPARAM=:H"
  T(02) = "DELETE FROM SAM_REAJUSTEPRC_ESTADO_DOT WHERE REAJUSTEPRCPARAM=:H"
  T(03) = "DELETE FROM SAM_REAJUSTEPRC_ESTADO_REG WHERE REAJUSTEPRCPARAM=:H"
  T(04) = "DELETE FROM SAM_REAJUSTEPRC_ESTADO_SL  WHERE REAJUSTEPRCPARAM=:H"
  T(05) = "DELETE FROM SAM_REAJUSTEPRC_MUNICIPIO_AN  WHERE REAJUSTEPRCPARAM=:H"
  T(06) = "DELETE FROM SAM_REAJUSTEPRC_MUNICIPIO_DOT WHERE REAJUSTEPRCPARAM=:H"
  T(07) = "DELETE FROM SAM_REAJUSTEPRC_MUNICIPIO_REG WHERE REAJUSTEPRCPARAM=:H"
  T(08) = "DELETE FROM SAM_REAJUSTEPRC_MUNICIPIO_SL  WHERE REAJUSTEPRCPARAM=:H"
  T(09) = "DELETE FROM SAM_REAJUSTEPRC_PRESTADOR_AN  WHERE REAJUSTEPRCPARAM=:H"
  T(10) = "DELETE FROM SAM_REAJUSTEPRC_PRESTADOR_DOT WHERE REAJUSTEPRCPARAM=:H"
  T(11) = "DELETE FROM SAM_REAJUSTEPRC_PRESTADOR_REG WHERE REAJUSTEPRCPARAM=:H"
  T(12) = "DELETE FROM SAM_REAJUSTEPRC_PRESTADOR_SL  WHERE REAJUSTEPRCPARAM=:H"
  T(13) = "DELETE FROM SAM_REAJUSTEPRC_REDE_AN  WHERE REAJUSTEPRCPARAM=:H"
  T(14) = "DELETE FROM SAM_REAJUSTEPRC_REDE_DOT WHERE REAJUSTEPRCPARAM=:H"
  T(15) = "DELETE FROM SAM_REAJUSTEPRC_REDE_REG WHERE REAJUSTEPRCPARAM=:H"
  T(16) = "DELETE FROM SAM_REAJUSTEPRC_REDE_SL  WHERE REAJUSTEPRCPARAM=:H"
  T(17) = "DELETE FROM SAM_REAJUSTEPRC_PARAMTIPO  WHERE REAJUSTEPRCPARAM=:H"

  SQL.Add("SELECT * FROM SAM_REAJUSTEPRC_PARAM WHERE REAJUSTEPRC = :REAJUSTEPRC")
  SQL.RequestLive = True
  SQL.ParamByName("REAJUSTEPRC").Value = CurrentQuery.FieldByName("HANDLE").AsInteger
  SQL.Active = True

  While Not SQL.EOF
    For i = 1 To 17
      DEL.Active = False
      DEL.Clear
      DEL.Add(T(i))
      DEL.ParamByName("H").Value = SQL.FieldByName("HANDLE").AsInteger
      DEL.ExecSQL
    Next i
    SQL.Delete
  Wend

  Set SQL = Nothing
  Set SQL = Nothing

End Sub
