'HASH: D978B0DB3D939962D6988DDEDB1601BB
'Macro: SAM_MIGRACAO_EQDEPENDENCIAS

Public Sub TABLE_BeforeEdit(cancontinue As Boolean)
	If WebMode Then
		DEPENDENTEDESTINO.WebLocalWhere = "A.CONTRATO = @CAMPO(CONTRATODESTINO)"
		DEPENDENTEORIGEM.WebLocalWhere = "A.CONTRATO = @CAMPO(CONTRATOORIGEM)" _
                                 		+ " ) AND A.HANDLE NOT IN (SELECT DEPENDENTEORIGEM FROM SAM_MIGRACAO_EQDEPENDENCIAS WHERE MIGRACAO = " _
                                 		+ " @CAMPO(MIGRACAO)"
	ElseIf VisibleMode Then
		DEPENDENTEDESTINO.LocalWhere = "SAM_CONTRATO_TPDEP.CONTRATO = @CONTRATODESTINO"
		DEPENDENTEORIGEM.LocalWhere = "SAM_CONTRATO_TPDEP.CONTRATO = @CONTRATOORIGEM" _
                                 	+ " ) AND SAM_CONTRATO_TPDEP.HANDLE NOT IN (SELECT DEPENDENTEORIGEM FROM SAM_MIGRACAO_EQDEPENDENCIAS WHERE MIGRACAO = " _
                                 	+ " @MIGRACAO"
	End If
End Sub

Public Sub TABLE_BeforeInsert(cancontinue As Boolean)
	If WebMode Then
		DEPENDENTEDESTINO.WebLocalWhere = "A.CONTRATO = @CAMPO(CONTRATODESTINO)"
		DEPENDENTEORIGEM.WebLocalWhere = "A.CONTRATO = @CAMPO(CONTRATOORIGEM)" _
                                 		+ " ) AND A.HANDLE NOT IN (SELECT DEPENDENTEORIGEM FROM SAM_MIGRACAO_EQDEPENDENCIAS WHERE MIGRACAO = " _
                                 		+ " @CAMPO(MIGRACAO)"
	ElseIf VisibleMode Then
		DEPENDENTEDESTINO.LocalWhere = "SAM_CONTRATO_TPDEP.CONTRATO = @CONTRATODESTINO"
		DEPENDENTEORIGEM.LocalWhere = "SAM_CONTRATO_TPDEP.CONTRATO = @CONTRATOORIGEM" _
                                 	+ " ) AND SAM_CONTRATO_TPDEP.HANDLE NOT IN (SELECT DEPENDENTEORIGEM FROM SAM_MIGRACAO_EQDEPENDENCIAS WHERE MIGRACAO = " _
                                 	+ " @MIGRACAO"
	End If
End Sub
