'HASH: C25BDF34C41355BF54141A4E4A0764F2
Option Explicit

Public Sub TIPODEPENDENTE_OnPopup(ShowPopup As Boolean)
  Dim vLocalWhere As String

  vLocalWhere = "A.GRUPODEPENDENTE <> 'T' AND A.HANDLE IN (SELECT TD.TIPODEPENDENTE FROM SAM_CONTRATO_TPDEP TD WHERE TD.CONTRATO = (SELECT CM.CONTRATO FROM SAM_CONTRATO_MOD CM " + _
                "JOIN SAM_CONTRATO_MOD_LIMCOB LC ON (LC.CONTRATOMODULO = CM.HANDLE) WHERE LC.HANDLE = " + CStr(CurrentQuery.FieldByName("CONTRATOMODULOLIMCOB").AsInteger) + " ))"

  TIPODEPENDENTE.LocalWhere = vLocalWhere
End Sub
