'HASH: CD2F5F63F8074444EDCE9D0BC00E2215

Public Sub TABLE_BeforeEdit(CanContinue As Boolean)
	If WebMode Then
		MODULO.WebLocalWhere = "A.HANDLE NOT IN (SELECT MODULO FROM SAM_MODEQUIVALENCIA_MOD WHERE MODEQUIVALENCIA = @CAMPO(MODEQUIVALENCIA))"
	ElseIf VisibleMode Then
		MODULO.LocalWhere = "SAM_MODULO.HANDLE NOT IN (SELECT MODULO FROM SAM_MODEQUIVALENCIA_MOD WHERE MODEQUIVALENCIA = @MODEQUIVALENCIA)"
	End If
End Sub

Public Sub TABLE_BeforeInsert(CanContinue As Boolean)
	If WebMode Then
		MODULO.WebLocalWhere = "A.HANDLE NOT IN (SELECT MODULO FROM SAM_MODEQUIVALENCIA_MOD WHERE MODEQUIVALENCIA = @CAMPO(MODEQUIVALENCIA))"
	ElseIf VisibleMode Then
		MODULO.LocalWhere = "SAM_MODULO.HANDLE NOT IN (SELECT MODULO FROM SAM_MODEQUIVALENCIA_MOD WHERE MODEQUIVALENCIA = @MODEQUIVALENCIA)"
	End If
End Sub
