'HASH: 734589E2DB14EF08AB1AC112EE498A9A
Public Sub CODIGOFOLHA_OnPopup(ShowPopup As Boolean)
	CODIGOFOLHA.LocalWhere = "HANDLE IN (SELECT CODIGOFOLHA FROM SFN_FOLHAPAGTO_TIPOFAT TF JOIN SFN_FOLHAPAGTO_TIPOFATCODFOLHA CF ON CF.FOLHAPAGAMENTOTIPOFAT = TF.HANDLE JOIN SFN_GRUPOSCODFOLHA GCF ON GCF.FOLHAPAGAMENTO = TF.FOLHAPAGAMENTO WHERE GCF.HANDLE = "+Str(CurrentQuery.FieldByName("GRUPOSCODIGOFOLHA").AsInteger)+" )"
End Sub
