'HASH: 140FCB9B43140BD9755496D84A8A7F58
 
Public Sub TABLE_AfterScroll()

    If WebMode Then
	  AGENTEVENDA.WebLocalWhere = "A.AGENCIAVENDAS = @CAMPO(AGENCIAVENDA)"
	Else
	  AGENTEVENDA.LocalWhere = "AGENCIAVENDAS = @AGENCIAVENDA"
	End If

End Sub
