'HASH: 5EC6FA8CC5C6E67F2CCF7AD1B07C29F8
 

Public Sub TABLE_AfterScroll()

    If WebMode Then
	  AGENTEVENDA.WebLocalWhere = "A.AGENCIAVENDAS = @CAMPO(AGENCIAVENDA)"
	Else
	  AGENTEVENDA.LocalWhere = "AGENCIAVENDAS = @AGENCIAVENDA"
	End If

End Sub
